# Brain-Ear Axis Analysis System Configuration

# Environment configuration
environment: development  # Options: development, testing, production

# Database configuration
databases:
  relational:
    type: postgresql
    host: localhost
    port: 5432
    database: brain_ear_axis
    username: postgres
    password: ${POSTGRES_PASSWORD}  # Set in environment variable
    pool_size: 10
    max_overflow: 20
    pool_recycle: 3600
    pool_timeout: 30

  document:
    type: mongodb
    host: localhost
    port: 27017
    database: brain_ear_axis
    username: mongo_user
    password: ${MONGO_PASSWORD}  # Set in environment variable
    authentication_database: admin
    
  object_storage:
    type: minio
    endpoint: localhost:9000
    access_key: ${MINIO_ACCESS_KEY}  # Set in environment variable
    secret_key: ${MINIO_SECRET_KEY}  # Set in environment variable
    secure: false  # Set to true for HTTPS
    buckets:
      - name: genomic-data
        versioning: true
      - name: microbiome-data
        versioning: true
      - name: neural-data
        versioning: true
      - name: analysis-results
        versioning: true

# API configuration
api:
  host: 0.0.0.0
  port: 8000
  debug: true
  log_level: info
  jwt_secret: ${JWT_SECRET}  # Set in environment variable
  jwt_expiration: 86400  # 24 hours in seconds
  cors_origins:
    - http://localhost:3000
    - http://localhost:8080
  rate_limit:
    requests_per_minute: 60

# Workflow orchestration
workflow:
  engine: nextflow
  executor: local  # Options: local, slurm, sge, pbs, lsf, k8s
  max_cpus: 8
  max_memory: 16GB
  tmp_dir: /tmp
  work_dir: /data/workflow_work
  container_engine: docker  # Options: docker, singularity, podman
  
  # Specific module configurations
  modules:
    genomic_analysis:
      container_image: brain-ear-axis/genomic-analysis:latest
      max_cpus: 16
      max_memory: 32GB
      
    microbiome_analysis:
      container_image: brain-ear-axis/microbiome-analysis:latest
      max_cpus: 8
      max_memory: 16GB
      
    neural_signal_analysis:
      container_image: brain-ear-axis/neural-signal-analysis:latest
      max_cpus: 8
      max_memory: 32GB
      gpu: true
      
    integrated_data_processing:
      container_image: brain-ear-axis/integrated-data-processing:latest
      max_cpus: 8
      max_memory: 64GB
      
    disease_localization:
      container_image: brain-ear-axis/disease-localization:latest
      max_cpus: 8
      max_memory: 32GB
      gpu: true
      
    personalized_analysis:
      container_image: brain-ear-axis/personalized-analysis:latest
      max_cpus: 4
      max_memory: 16GB

# UI configuration
ui:
  host: 0.0.0.0
  port: 3000
  api_url: http://localhost:8000
  enable_analytics: false
  
# Logging configuration
logging:
  version: 1
  formatters:
    standard:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: standard
      stream: ext://sys.stdout
    file:
      class: logging.handlers.RotatingFileHandler
      level: INFO
      formatter: standard
      filename: /var/log/brain-ear-axis/app.log
      maxBytes: 10485760  # 10MB
      backupCount: 10
  loggers:
    '':  # Root logger
      level: INFO
      handlers: [console, file]
      propagate: false
    'uvicorn':
      level: INFO
    'sqlalchemy.engine':
      level: WARNING
